[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
  publish = "staticfiles"

[build.environment]
  DJANGO_SETTINGS_MODULE = "todolistweb.settings"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
